# Generated by Django 3.2.3 on 2021-05-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortText',
            fields=[
                ('text_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('text', models.TextField()),
                ('viewcount', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['viewcount', 'created'],
            },
        ),
    ]
