# Generated by Django 3.2.3 on 2021-05-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shorttext',
            options={'ordering': ['-created']},
        ),
    ]
